### ISSUE TITLE
[Requested By Grid]: Addition of grid to grid list

### ISSUE THREAD

**Issue by andsim** [Virtual-Universe/Universe-Viewer-Early-Dev#1]
i am current on opensim atm but i planning switch to ur platform as sooner it is ready here detail my current detail

    <key>login.anskygrid.ca:8002</key>
        <map>
        <key>LastModified</key>
            <date>2019-12-04T01:12:09.06Z</date>
        <key>about</key>
            <string>http://www.ansky.ca/about/</string>
        <key>gatekeeper</key>
            <string>login.anskygrid.ca:8002</string>
        <key>gridname</key>
            <string>AnSky Grid</string>
        <key>gridnick</key>
            <string>anskygrid</string>
        <key>helperuri</key>
            <string>http://www.anskygrid.ca/economy/</string>
        <key>login_identifier_types</key>
            <array>
                <string>agent</string>
                <string>account</string>
            </array>
        <key>loginpage</key>
            <string>http://www.anskygrid.ca/loginscreen/</string>
        <key>loginuri</key>
            <array>
                <string>http://login.anskygrid.ca:8002/</string>
            </array>
        <key>name</key>
            <string>login.anskygrid.ca:8002</string>
        <key>password</key>
            <string>https://anskygrid.ca/index.php/register?view=reset</string>
        <key>platform</key>
            <string>OpenSim</string>
        <key>register</key>
            <string>https://anskygrid.ca/index.php/component/users/?view=registration&amp;Itemid=101</string>
        <key>slurl_base</key>
            <string>hop://login.anskygrid.ca:8002/</string>
        <key>web_profile_url</key>
            <undef />
        </map>

**Comment by BriaKallistaStarfinder** [comment]
Aloha,

We will definitely add your grid to the list of grids in the new viewer.  When our new grid architecture is released and you have switched over please be sure to let us know via this issue tracker to let us know that your grid has made the switch so we can be sure your grid info is updated with the correct information.

Best regards,

Best regards,

Briakallista Starfinder
Member Roles: Core Developer, Member governing body
Member Responsibilities: Roleplay lifestyles Development, Maintenance,
Viewer Development
Work Groups: Grid Architecture Development, Viewer Development
Virtual World Research Inc.

**Comment by andsim** [comment]
oh i will update when Architecture is release

**Comment by BriaKallistaStarfinder** [comment]
Aloha,

The grid has been added to the list.  When the first build release comes out the grid will appear in the default grids list in the grid manager.

Best regards,

Briakallista Starfinder
Member Roles: Core Developer, Member governing body
Member Responsibilities: Roleplay lifestyles Development, Maintenance,
Viewer Development
Work Groups: Grid Architecture Development, Viewer Development
Virtual World Research Inc.
